[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.primary]
background = "#000107"
foreground = "#839496"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Source Code Pro"

[scrolling]
history = 0
multiplier = 0

[window]
dynamic_title = true
# gtk_theme_variant = "None"
opacity = 0.81

[window.class]
general = "terminal"
instance = "terminal"
