#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  # shellcheck disable=1090
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# shellcheck disable=2155
export MPD_HOST="$(grep -Po '(?<=^password ")[^@]*' "$SCRIPT_ROOT/config/mpd/password.conf")@localhost"
export GTK_THEME=Arc:dark GTK2_RC_FILES=/usr/share/themes/Arc-dark/gtk-2.0/gtkrc QT_STYLE_OVERRIDE=Adwaita-Dark

numlockx on
[ -f ~/.Xresources  ] && xrdb -merge -I"$HOME" ~/.Xresources

setxkbmap -option shift:both_capslock
setxkbmap -option caps:ctrl_modifier
setxkbmap -option compose:rctrl-altgr
setxkbmap -option compose:lwin-altgr
setxkbmap -option compose:prsc
xcape -e 'Caps_Lock=Escape;Control_R=Menu' -t 210
xbindkeys
xrandr --dpi 80

dbus-update-activation-environment --systemd DISPLAY
eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)"
eval "$(ssh-agent -s)"
export SSH_AUTH_SOCK

case "$USE_WM" in
    gnome)
        exec gnome-session
        ;;
    *)
        exec i3
esac
# vim: filetype=sh
