[menu]
executable = "swayr-rofi"
args = [
    "{prompt}",
]

[format]
output_format = '{indent}<b>Output {name}</b>    <span alpha="20000">({id})</span>'
workspace_format = "» <b>Workspace {name}</b> on output {output_name}    <span alpha=\"30%\">({id})</span>"
container_format = '› <b>Container</b> <i>{marks}</i> on workspace {workspace_name}    <span alpha="30%">({id})</span>'
window_format = "<i>{app_name}</i> — {urgency_start}<b>“{title}”</b>{urgency_end} <i>{marks}</i>   <span alpha=\"30%\">{workspace_name} / {output_name} ({id})</span>\u0000icon\u001F{app_icon}"
indent = "    "
urgency_start = '<span background="darkred" foreground="yellow">'
urgency_end = "</span>"
html_escape = true
icon_dirs = [
    "/usr/share/icons/hicolor/apps",
    "/usr/share/icons/hicolor/symbolic/apps",
    "/usr/share/icons/hicolor/scalable/apps",
    "/usr/share/icons/hicolor/1024x1024/apps",
    "/usr/share/icons/hicolor/256x256/apps",
    "/usr/share/icons/hicolor/192x192/apps",
    "/usr/share/icons/hicolor/128x128/apps",
    "/usr/share/icons/hicolor/96x96/apps",
    "/usr/share/icons/hicolor/72x72/apps",
    "/usr/share/icons/hicolor/64x64/apps",
    "/usr/share/icons/hicolor/48x48/apps",
    "/usr/share/icons/hicolor/36x36/apps",
    "/usr/share/icons/hicolor/32x32/apps",
    "/usr/share/icons/hicolor/24x24/apps",
    "/usr/share/icons/hicolor/22x22/apps",
    "/usr/share/icons/hicolor/48x48/apps",
    "/usr/share/icons/Adwaita/64x64/apps",
    "/usr/share/icons/Adwaita/48x48/apps",
    "/usr/share/icons/Adwaita/22x22/apps",
    "/usr/share/pixmaps",
]

[layout]
auto_tile = false
auto_tile_min_window_width_per_output_width = [
    [800, 400],
    [1024, 500],
    [1280, 600],
    [1400, 680],
    [1440, 700],
    [1600, 780],
    [1680, 780],
    [1920, 920],
    [2048, 980],
    [2560, 1000],
    [3440, 1200],
    [3840, 1280],
    [4096, 1400],
    [4480, 1600],
    [7680, 2400],
]

[focus]
lockin_delay = 0

[misc]
seq_inhibit = false

[swaymsg_commands]
include_predefined = true
