#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi
choose=1
if [[ $1 == "--choose" ]]; then
    choose="$2"
    shift 2
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

case "$password" in
    ssh/*)
        expect - -- \
        "$(pass show "$password" | sed -n 's,\($HOME\|~\),'"$HOME"',g;2p')" \
        "$(pass show "$password" | sed -n '1p')" << "EOF"
        set file [lindex $argv 0]
        set password [lindex $argv 1]
        spawn ssh-add "$file"
        expect "Enter passphrase for $file:"
        send "$password\n"
        expect "Identity added: $file *"
        wait
        close
EOF
    ;;
esac

if [[ $typeit -eq 0 ]]; then
    pass show -c"$choose" "$password" 2>/dev/null
else
    delay=48 # in ms
    typecmd='\x00type\x00--clearmodifiers\x00--delay\x00'"$delay"'\x00'
    keycmd='\x00sleep\x00'"$(printf 'scale=3;%s/1000\n' "$delay"| bc)"'\x00key\x00--clearmodifiers\x00'
    pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
        sed 's/[^`^´~]\+/'"$typecmd"'&/g
             s/\^/'"$keycmd"'asciicircum/g
             s/`/'"$keycmd"'grave/g
             s/´/'"$keycmd"'acute/g
             s/~/'"$keycmd"'asciitilde/g' |
        sed 's/^\x00*//' |
        xargs -0 -n 5 xdotool
fi
